# A first workflow to play around with the editor
name: Develop in branch
on: [pull_request, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: |
          echo "Workflow triggered in branch '${{ github.ref }}'."
          echo "Workflow triggered in branch '${{ github.event_name }}'." 
          echo "Workflow triggered in branch '${{ github.actor }}'."
          echo "PR title is '${{ github.event.pull_request.title }}'."
          echo "::debug::This is a debug message."
          echo "::notice::This is a notice message."
          echo "::warning::This is a warning message."
          echo "::error::This is an error message."
      - uses: actions/checkout@v4.2.2
      - uses: devops-actions/actionlint@v0.1.3
